name: tic_tac_toe
description: "Tic Tac Toe Game"
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.2.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_app_name: ^0.1.1
  flutter_launcher_icons: ^0.11.0
  flutter_native_splash: ^2.2.0+1

flutter_app_name:
  name: 'Tic Tac Toe'

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "favicon.png"
  min_sdk_android: 21
  adaptive_icon_background: '#50206c'
  adaptive_icon_foreground: 'favicon.png'
  web:
    generate: true
    image_path: "favicon.png"
    background_color: "#50206c"
    theme_color: "#50206c"
  windows:
    generate: true
    image_path: "favicon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "favicon.png"

flutter_native_splash:
  color: "#50206c"
  image: favicon.png
  android_12:
    image: favicon.png
    color: "#50206c"
    icon_background_color: "#50206c"
    android: true
    ios: true
    web: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true